dataset:
  raw_path: "../data/raw/02_Used_Car_Prices.xlsx"
  processed_train_path: "../processed/train.csv"
  processed_test_path: "../processed/test.csv"
  numeric_features: ["Year", "Kilometers_Driven", "Mileage", "Engine", "Power", "Seats"]
  categorical_features: ["Brand_Model", "Location", "Fuel_Type", "Transmission", "Owner_Type"]
  test_size: 0.2

training:
  normalize: True
  feature_selection: True
  session_id: 42
  log_experiment: True
  bin_features: ["Year", "Kilometers_Driven", "Mileage", "Engine", "Power", "Seats"]

model:
  auto_select: True  
  type: "catboost" 
  output_path: "../models/final_used_car_model.pkl"
